---
# Handlers for MessageBroker deployment

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start etcd
  systemd:
    name: etcd
    state: started

- name: Restart messagebroker
  systemd:
    name: messagebroker
    state: restarted
