// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: pkg/pb/messagebroker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageBroker_CreateTopic_FullMethodName      = "/pb.MessageBroker/CreateTopic"
	MessageBroker_ProduceMessage_FullMethodName   = "/pb.MessageBroker/ProduceMessage"
	MessageBroker_ConsumeMessages_FullMethodName  = "/pb.MessageBroker/ConsumeMessages"
	MessageBroker_GetTopicMetadata_FullMethodName = "/pb.MessageBroker/GetTopicMetadata"
	MessageBroker_BrokerMetadata_FullMethodName   = "/pb.MessageBroker/BrokerMetadata"
)

// MessageBrokerClient is the client API for MessageBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageBrokerClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	ProduceMessage(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
	ConsumeMessages(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	GetTopicMetadata(ctx context.Context, in *GetTopicMetadataRequest, opts ...grpc.CallOption) (*TopicMetadata, error)
	BrokerMetadata(ctx context.Context, in *BrokerMetadataRequest, opts ...grpc.CallOption) (*BrokerMetadataResponse, error)
}

type messageBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBrokerClient(cc grpc.ClientConnInterface) MessageBrokerClient {
	return &messageBrokerClient{cc}
}

func (c *messageBrokerClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, MessageBroker_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) ProduceMessage(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, MessageBroker_ProduceMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) ConsumeMessages(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeResponse)
	err := c.cc.Invoke(ctx, MessageBroker_ConsumeMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) GetTopicMetadata(ctx context.Context, in *GetTopicMetadataRequest, opts ...grpc.CallOption) (*TopicMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicMetadata)
	err := c.cc.Invoke(ctx, MessageBroker_GetTopicMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) BrokerMetadata(ctx context.Context, in *BrokerMetadataRequest, opts ...grpc.CallOption) (*BrokerMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerMetadataResponse)
	err := c.cc.Invoke(ctx, MessageBroker_BrokerMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBrokerServer is the server API for MessageBroker service.
// All implementations must embed UnimplementedMessageBrokerServer
// for forward compatibility.
type MessageBrokerServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	ProduceMessage(context.Context, *ProduceRequest) (*ProduceResponse, error)
	ConsumeMessages(context.Context, *ConsumeRequest) (*ConsumeResponse, error)
	GetTopicMetadata(context.Context, *GetTopicMetadataRequest) (*TopicMetadata, error)
	BrokerMetadata(context.Context, *BrokerMetadataRequest) (*BrokerMetadataResponse, error)
	mustEmbedUnimplementedMessageBrokerServer()
}

// UnimplementedMessageBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageBrokerServer struct{}

func (UnimplementedMessageBrokerServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedMessageBrokerServer) ProduceMessage(context.Context, *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProduceMessage not implemented")
}
func (UnimplementedMessageBrokerServer) ConsumeMessages(context.Context, *ConsumeRequest) (*ConsumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeMessages not implemented")
}
func (UnimplementedMessageBrokerServer) GetTopicMetadata(context.Context, *GetTopicMetadataRequest) (*TopicMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicMetadata not implemented")
}
func (UnimplementedMessageBrokerServer) BrokerMetadata(context.Context, *BrokerMetadataRequest) (*BrokerMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrokerMetadata not implemented")
}
func (UnimplementedMessageBrokerServer) mustEmbedUnimplementedMessageBrokerServer() {}
func (UnimplementedMessageBrokerServer) testEmbeddedByValue()                       {}

// UnsafeMessageBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBrokerServer will
// result in compilation errors.
type UnsafeMessageBrokerServer interface {
	mustEmbedUnimplementedMessageBrokerServer()
}

func RegisterMessageBrokerServer(s grpc.ServiceRegistrar, srv MessageBrokerServer) {
	// If the following call panics, it indicates UnimplementedMessageBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageBroker_ServiceDesc, srv)
}

func _MessageBroker_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_ProduceMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).ProduceMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_ProduceMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).ProduceMessage(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_ConsumeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).ConsumeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_ConsumeMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).ConsumeMessages(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_GetTopicMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).GetTopicMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_GetTopicMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).GetTopicMetadata(ctx, req.(*GetTopicMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_BrokerMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).BrokerMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_BrokerMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).BrokerMetadata(ctx, req.(*BrokerMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageBroker_ServiceDesc is the grpc.ServiceDesc for MessageBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MessageBroker",
	HandlerType: (*MessageBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _MessageBroker_CreateTopic_Handler,
		},
		{
			MethodName: "ProduceMessage",
			Handler:    _MessageBroker_ProduceMessage_Handler,
		},
		{
			MethodName: "ConsumeMessages",
			Handler:    _MessageBroker_ConsumeMessages_Handler,
		},
		{
			MethodName: "GetTopicMetadata",
			Handler:    _MessageBroker_GetTopicMetadata_Handler,
		},
		{
			MethodName: "BrokerMetadata",
			Handler:    _MessageBroker_BrokerMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/messagebroker.proto",
}
