// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/pb/messagebroker.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTopicRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NumPartitions     int32                  `protobuf:"varint,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *CreateTopicRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    int32                  `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicResponse) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,4,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetTopicMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicMetadataRequest) Reset() {
	*x = GetTopicMetadataRequest{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicMetadataRequest) ProtoMessage() {}

func (x *GetTopicMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetTopicMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopicMetadataRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PartitionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Leader        int32                  `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Replicas      []int32                `protobuf:"varint,3,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	Isr           []int32                `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{8}
}

func (x *PartitionMetadata) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionMetadata) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *PartitionMetadata) GetReplicas() []int32 {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionMetadata) GetIsr() []int32 {
	if x != nil {
		return x.Isr
	}
	return nil
}

type TopicMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []*PartitionMetadata   `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMetadata) Reset() {
	*x = TopicMetadata{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetadata) ProtoMessage() {}

func (x *TopicMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMetadata.ProtoReflect.Descriptor instead.
func (*TopicMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{9}
}

func (x *TopicMetadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicMetadata) GetPartitions() []*PartitionMetadata {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type BrokerMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerMetadataRequest) Reset() {
	*x = BrokerMetadataRequest{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerMetadataRequest) ProtoMessage() {}

func (x *BrokerMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerMetadataRequest.ProtoReflect.Descriptor instead.
func (*BrokerMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{10}
}

type BrokerMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,4,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerMetadataResponse) Reset() {
	*x = BrokerMetadataResponse{}
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerMetadataResponse) ProtoMessage() {}

func (x *BrokerMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_messagebroker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerMetadataResponse.ProtoReflect.Descriptor instead.
func (*BrokerMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_messagebroker_proto_rawDescGZIP(), []int{11}
}

func (x *BrokerMetadataResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrokerMetadataResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BrokerMetadataResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BrokerMetadataResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

var File_pkg_pb_messagebroker_proto protoreflect.FileDescriptor

const file_pkg_pb_messagebroker_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/pb/messagebroker.proto\x12\x02pb\"\x80\x01\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0enum_partitions\x18\x02 \x01(\x05R\rnumPartitions\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\"e\n" +
	"\x13CreateTopicResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\x05R\n" +
	"partitions\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"l\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"]\n" +
	"\x0fProduceResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\x7f\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12!\n" +
	"\fmax_messages\x18\x04 \x01(\x05R\vmaxMessages\"I\n" +
	"\aMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"n\n" +
	"\x0fConsumeResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12'\n" +
	"\bmessages\x18\x03 \x03(\v2\v.pb.MessageR\bmessages\"/\n" +
	"\x17GetTopicMetadataRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"i\n" +
	"\x11PartitionMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\x05R\x06leader\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\x05R\breplicas\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\x05R\x03isr\"\\\n" +
	"\rTopicMetadata\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x125\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x15.pb.PartitionMetadataR\n" +
	"partitions\"\x17\n" +
	"\x15BrokerMetadataRequest\"o\n" +
	"\x16BrokerMetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x04 \x01(\bR\tisHealthy2\xd3\x02\n" +
	"\rMessageBroker\x12>\n" +
	"\vCreateTopic\x12\x16.pb.CreateTopicRequest\x1a\x17.pb.CreateTopicResponse\x129\n" +
	"\x0eProduceMessage\x12\x12.pb.ProduceRequest\x1a\x13.pb.ProduceResponse\x12:\n" +
	"\x0fConsumeMessages\x12\x12.pb.ConsumeRequest\x1a\x13.pb.ConsumeResponse\x12B\n" +
	"\x10GetTopicMetadata\x12\x1b.pb.GetTopicMetadataRequest\x1a\x11.pb.TopicMetadata\x12G\n" +
	"\x0eBrokerMetadata\x12\x19.pb.BrokerMetadataRequest\x1a\x1a.pb.BrokerMetadataResponseB)Z'github.com/dhruvit2/messagebroker/pkg/pbb\x06proto3"

var (
	file_pkg_pb_messagebroker_proto_rawDescOnce sync.Once
	file_pkg_pb_messagebroker_proto_rawDescData []byte
)

func file_pkg_pb_messagebroker_proto_rawDescGZIP() []byte {
	file_pkg_pb_messagebroker_proto_rawDescOnce.Do(func() {
		file_pkg_pb_messagebroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_messagebroker_proto_rawDesc), len(file_pkg_pb_messagebroker_proto_rawDesc)))
	})
	return file_pkg_pb_messagebroker_proto_rawDescData
}

var file_pkg_pb_messagebroker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_pb_messagebroker_proto_goTypes = []any{
	(*CreateTopicRequest)(nil),      // 0: pb.CreateTopicRequest
	(*CreateTopicResponse)(nil),     // 1: pb.CreateTopicResponse
	(*ProduceRequest)(nil),          // 2: pb.ProduceRequest
	(*ProduceResponse)(nil),         // 3: pb.ProduceResponse
	(*ConsumeRequest)(nil),          // 4: pb.ConsumeRequest
	(*Message)(nil),                 // 5: pb.Message
	(*ConsumeResponse)(nil),         // 6: pb.ConsumeResponse
	(*GetTopicMetadataRequest)(nil), // 7: pb.GetTopicMetadataRequest
	(*PartitionMetadata)(nil),       // 8: pb.PartitionMetadata
	(*TopicMetadata)(nil),           // 9: pb.TopicMetadata
	(*BrokerMetadataRequest)(nil),   // 10: pb.BrokerMetadataRequest
	(*BrokerMetadataResponse)(nil),  // 11: pb.BrokerMetadataResponse
}
var file_pkg_pb_messagebroker_proto_depIdxs = []int32{
	5,  // 0: pb.ConsumeResponse.messages:type_name -> pb.Message
	8,  // 1: pb.TopicMetadata.partitions:type_name -> pb.PartitionMetadata
	0,  // 2: pb.MessageBroker.CreateTopic:input_type -> pb.CreateTopicRequest
	2,  // 3: pb.MessageBroker.ProduceMessage:input_type -> pb.ProduceRequest
	4,  // 4: pb.MessageBroker.ConsumeMessages:input_type -> pb.ConsumeRequest
	7,  // 5: pb.MessageBroker.GetTopicMetadata:input_type -> pb.GetTopicMetadataRequest
	10, // 6: pb.MessageBroker.BrokerMetadata:input_type -> pb.BrokerMetadataRequest
	1,  // 7: pb.MessageBroker.CreateTopic:output_type -> pb.CreateTopicResponse
	3,  // 8: pb.MessageBroker.ProduceMessage:output_type -> pb.ProduceResponse
	6,  // 9: pb.MessageBroker.ConsumeMessages:output_type -> pb.ConsumeResponse
	9,  // 10: pb.MessageBroker.GetTopicMetadata:output_type -> pb.TopicMetadata
	11, // 11: pb.MessageBroker.BrokerMetadata:output_type -> pb.BrokerMetadataResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_messagebroker_proto_init() }
func file_pkg_pb_messagebroker_proto_init() {
	if File_pkg_pb_messagebroker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_messagebroker_proto_rawDesc), len(file_pkg_pb_messagebroker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_messagebroker_proto_goTypes,
		DependencyIndexes: file_pkg_pb_messagebroker_proto_depIdxs,
		MessageInfos:      file_pkg_pb_messagebroker_proto_msgTypes,
	}.Build()
	File_pkg_pb_messagebroker_proto = out.File
	file_pkg_pb_messagebroker_proto_goTypes = nil
	file_pkg_pb_messagebroker_proto_depIdxs = nil
}
